# https://gleam.run/writing-gleam/gleam-toml/.
name = "gecko"
version = "1.0.0"
description = "ğŸ¦ audio transcription for any scale"

licences = ["Apache-2.0"]
repository = { type = "github", user = "daniellionel01", repo = "gecko" }
links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
