# https://gleam.run/writing-gleam/gleam-toml/.
name = "gecko"
version = "1.0.0"
description = "ğŸ¦ audio transcription for any scale"

licences = ["Apache-2.0"]
repository = { type = "github", user = "daniellionel01", repo = "gecko" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
sqlight = ">= 1.0.3 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
parrot = ">= 2.1.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
